from pprint import pprint
import base_data

pprint(base_data.ALL_POKE_NAMES)
print("--- ---")
print("--- ---")
print("--- ---")
pprint(base_data.ALL_MOVE_NAMES)
print("--- ---")
print("--- ---")
print("--- ---")
pprint(base_data.HALF_HEAL_MOVE_NAMES)
print("--- ---")
print("--- ---")
print("--- ---")
pprint(base_data.ONE_HIT_KO_MOVE_NAMES)
print("--- ---")
print("--- ---")
print("--- ---")
pprint(base_data.TWO_ATTACK_MOVE_NAMES)
print("--- ---")
print("--- ---")
print("--- ---")
pprint(base_data.MIN_TWO_MAX_FIVE_ATTACK_MOVE_NAMES)
print("--- ---")
print("--- ---")
print("--- ---")
pprint(base_data.MAX_THREE_ATTACK_MOVE_NAMES)
print("--- ---")
print("--- ---")
print("--- ---")
pprint(base_data.ALL_NATURES)
print("--- ---")
print("--- ---")
print("--- ---")
pprint(base_data.ALL_ITEMS)
print("--- ---")
print("--- ---")
print("--- ---")
pprint(base_data.ALL_TYPES)
print("--- ---")
print("--- ---")
print("--- ---")
pprint(base_data.POKEDEX)
print("--- ---")
print("--- ---")
print("--- ---")
pprint(base_data.MOVEDEX)
print("--- ---")
print("--- ---")
print("--- ---")
pprint(base_data.NATUREDEX)
print("--- ---")
print("--- ---")
print("--- ---")
pprint(base_data.TYPEDEX)
